global:
  useCombinedDb: true
  externalUrl: http://k8s-dev.oznome.csiro.au
  rollingUpdate:
    maxUnavailable: 1
  image:
    pullPolicy: Always
    tag: "0.0.36"
gateway:
  image:
    repository: "gcr.io/knowledge-network-192205/data61"
    tag: "latest"
  loadBalancerIP: "35.201.0.106"
  auth:
    facebookClientId: ""
    googleClientId: "1049152486192-csgrnu1jcp9u8qoja90rbn3s5fpot5mh.apps.googleusercontent.com"
    aafClientUri: "https://rapid.test.aaf.edu.au/jwt/authnrequest/research/IeiWdzrJ47-eSowf3rfLTQ"
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 250Mi
combined-db:
  resources:
    requests:
      cpu: 400m
      memory: 1000Mi
    limits:
      cpu: 1000m
      memory: 1500Mi
elasticsearch:
  data:
    storageClass: "standard"
    heapSize: 500m
    resources:
      requests:
        cpu: 400m
        memory: 1000Mi
      limits:
        cpu: 1000m
        memory: 1500Mi
indexer:
  resources:
    requests:
      cpu: 0
      memory: 0
    limits:
      cpu: 200m
      memory: 1000Mi
preview-map:
  resources:
    requests:
      cpu: 0
      memory: 0
    limits:
      cpu: 200m
      memory: 150Mi
registry-datastore:
    data:
        storageClass: "standard"
registry-api:
  resources:
    requests:
      cpu: 0
      memory: 0
    limits:
      cpu: 200m
      memory: 1000Mi
search-api:
  resources:
    requests:
      cpu: 0
      memory: 0
    limits:
      cpu: 200m
      memory: 1000Mi
web-server:
  image:
    repository: "gcr.io/knowledge-network-192205/data61"
    tag: "latest"
  resources:
    requests:
      cpu: 0
      memory: 0
    limits:
      cpu: 200m
      memory: 150Mi
sleuther-linked-data-rating:
  resources:
    requests:
      cpu: 0
      memory: 0
    limits:
      cpu: 200m
      memory: 150Mi
sleuther-broken-link:
  resources:
    requests:
      cpu: 0
      memory: 0
    limits:
      cpu: 200m
      memory: 150Mi
sleuther-visualization:
  resources:
    requests:
      cpu: 0
      memory: 0
    limits:
      cpu: 200m
      memory: 300Mi
admin-api:
  resources:
    requests:
      cpu: 0
      memory: 0
    limits:
      cpu: 200m
      memory: 150Mi
authorization-api:
  data:
    storageClass: "standard"
  resources:
    requests:
      cpu: 0
      memory: 0
    limits:
      cpu: 200m
      memory: 150Mi
discussions-api:
  resources:
    requests:
      cpu: 0
      memory: 0
    limits:
      cpu: 200m
      memory: 150Mi
