apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.org/ssl-services: {{ .Values.targetService | default "gateway" }}
  name: dev-ingress
spec:
  # tls:
  #   - hosts:
  #     - {{ .Values.hostname }}
  #     secretName: tls-certificate
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.targetService | default "gateway" }}
          servicePort: 80
        path: /