apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
  generation: 2
  name: kn-ingress
spec:
  rules:
  - host: dev.knowledgenet.co
    http:
      paths:
      - backend:
          serviceName: gateway
          servicePort: 80
        path: /
  tls:
   - secretName: kn-tls-secret-v41
     hosts:
     - dev.knowledgenet.co